### ISSUE TITLE
Pipeline runner removes work directory regardless of job success / fail

### ISSUE THREAD

**Issue by bcmcpher** [nipoppy/nipoppy#297]
It should keep working directory on pipeline failure to easily resume - currently it always deletes.

Ideally we can have it remove on success but have a flag to keep working directory regardless (for dev / testing new tools).

Snippet I think is the problem is here.
https://github.com/neurodatascience/nipoppy/blob/main/nipoppy_cli/nipoppy/workflows/runner.py#L209-L214

**Comment by michellewang** [comment]
Once #261 is merged, `BasePipelineWorkflow` (which is inherited by `PipelineRunner`, which in turn is inherited by `BidsConversionRunner`) will have attributes `n_success` and `n_total`. We can update the code in `PipelineRunner` so that the working directory is only deleted if `n_success` is equal to `n_total`.

**Comment by michellewang** [comment]
@bcmcpher please assign yourself if you want to work on this!
